[package]
name = "calc_core"
version = "0.1.0"
authors = ["Hikotaro Abe <netseed@seedcreate.onmicrosoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
